---
- hosts: webservers
  become: true
  gather_facts: true
  roles:
    - role: install_packages
      tags: install_packages
    - role: firewall
      tags: firewall
    - role: edit_index
      tags: edit_index
